<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $products = [
            [
                'product_type_id' => 1,
                'manufacturer_id' => 1,
                'name' => 'Apollo’s Whisper',
                'description' => 'A finely crafted longbow, said to channel the precision of the god of archery himself.',
                'img1' => 'assets/images/bows/HOYT-PRO-FORCE-COMPOUND-BOW3-2536972794.png',
                'img2' => 'assets/images/bows/PSE-Mini-Burner-2721639842.png',
                'img3' => 'assets/images/bows/212719_ts-747369128.png',
                'img4' => 'assets/images/bows/lazecky-skaut-padouk-dlouhy-luk-02.webp',
                'price' => 299.99,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 2,
                'name' => "Artemis' Grace",
                'description' => 'Elegant and deadly, this bow brings the silent power of the huntress to your grip.',
                'img1' => 'assets/images/bows/products_whitetail.png',
                'img2' => 'assets/images/bows/Kartal__71859.webp',
                'img3' => 'assets/images/bows/HOYT-PREVAIL-40-X3-COMPOUND-BOW-2072289325.png',
                'img4' => 'assets/images/bows/154124_ts-2558425600.png',
                'price' => 349.5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 3,
                'name' => 'Herculean Draw',
                'description' => 'Only the strongest can tame this massive recurve bow forged with mythical force.',
                'img1' => 'assets/images/bows/HOYT-PREVAIL-40-X3-COMPOUND-BOW-2072289325.png',
                'img2' => 'assets/images/bows/cobrat.png',
                'img3' => 'assets/images/bows/721ce995a25e003b69ce1fa0d07bb6f0-4038707716.png',
                'img4' => 'assets/images/bows/lazecky-skaut-padouk-dlouhy-luk-02.webp',
                'price' => 399.0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 4,
                'name' => 'Zeus’ Thunderstring',
                'description' => 'Crackling with energy, this compound bow delivers godlike power in each shot.',
                'img1' => 'assets/images/bows/721c7978-27bc-44ed-b8fd-84c33ffe7852_1.fb69e1ba4af568d34482fdcdf4fa80b8-3879175831.png',
                'img2' => 'assets/images/bows/BOWTECH-PRISM-COMPOUND-BOW-1200x1200-3708259902.png',
                'img3' => 'assets/images/bows/Symphony-1-3__45616.jpg',
                'img4' => 'assets/images/bows/A1yONs9p1HL._SL1500_-14-315219135.png',
                'price' => 479.95,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 5,
                'name' => 'Bow of Delphi',
                'description' => 'Used in ancient rites, this bow is as mysterious as the oracle’s visions.',
                'img1' => 'assets/images/bows/products_whitetail.png',
                'img2' => 'assets/images/bows/Kartal__71859.webp',
                'img3' => 'assets/images/bows/Ghost_Front__86345.webp',
                'img4' => 'assets/images/bows/1742942582628.jpg',
                'price' => 275.75,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 1,
                'name' => "Eros' Kiss",
                'description' => 'Graceful and lightweight, ideal for precision and elegance over brute force.',
                'img1' => 'assets/images/bows/154124_ts-2558425600.png',
                'img2' => 'assets/images/bows/721c7978-27bc-44ed-b8fd-84c33ffe7852_1.fb69e1ba4af568d34482fdcdf4fa80b8-3879175831.png',
                'img3' => 'assets/images/bows/products_falcon_impugnatura.png',
                'img4' => 'assets/images/bows/1742942582628.jpg',
                'price' => 259.99,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 2,
                'name' => 'Odysseus’ Curve',
                'description' => 'Styled after the legendary bow strung only by the hero Odysseus.',
                'img1' => 'assets/images/bows/lazecky-skaut-padouk-dlouhy-luk-04.webp',
                'img2' => 'assets/images/bows/Ghost_Front__86345.webp',
                'img3' => 'assets/images/bows/Immortal_Riser_Park__05856.jpg',
                'img4' => 'assets/images/bows/154124_ts-2558425600.png',
                'price' => 365.0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 3,
                'name' => 'Theban Phantom',
                'description' => 'A bow designed to vanish with its wielder, swift and spectral.',
                'img1' => 'assets/images/bows/Skylark__55835.png',
                'img2' => 'assets/images/bows/lazecky-skaut-padouk-dlouhy-luk-02.webp',
                'img3' => 'assets/images/bows/HOYT-PRO-FORCE-COMPOUND-BOW.jpg2_-1372812725.png',
                'img4' => 'assets/images/bows/1742942691467.jpg',
                'price' => 310.45,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 4,
                'name' => 'Titanfall Recurve',
                'description' => 'Built to withstand the might of a titan, this bow blends tradition and tech.',
                'img1' => 'assets/images/bows/Kartal_front__57995.webp',
                'img2' => 'assets/images/bows/1742942691467.jpg',
                'img3' => 'assets/images/bows/588649_ts-159236892.png',
                'img4' => 'assets/images/bows/2.-Siege-SAS-Compound-Bow--1857717526.png',
                'price' => 525.6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_type_id' => 1,
                'manufacturer_id' => 5,
                'name' => 'Oracle’s String',
                'description' => 'Engraved with cryptic symbols, said to guide its arrows true.',
                'img1' => 'assets/images/bows/products_falcon_impugnatura.png',
                'img2' => 'assets/images/bows/1742942582628.jpg',
                'img3' => 'assets/images/bows/products_whitetail.png',
                'img4' => 'assets/images/bows/Kartal_Side__92812.webp',
                'price' => 289.89,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Apollos Wrath',
                'description' => 'Inspired by the god of archery, this crossbow delivers sunlit precision.',
                'price' => 179.99,
                'manufacturer_id' => 3,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/armbrust-tactical_xlt_extra-2440-280988007.png',
                'img2' => 'assets/images/crossbows/607600_ts-213210129.png',
                'img3' => 'assets/images/crossbows/292144_ts-2963351509.png',
                'img4' => 'assets/images/crossbows/d6f8cb2488ec74d17076b267fc8daa63--crossbow-survival-gear-3605650570.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hades Whisper',
                'description' => 'A silent, lethal tool echoing the shadows of the underworld.',
                'price' => 159.99,
                'manufacturer_id' => 2,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/armbrust-big-dean-2-black-4249-2552608835.png',
                'img2' => 'assets/images/crossbows/crossbow-scaled-1572675912.png',
                'img3' => 'assets/images/crossbows/5831186_Pic2-2310902078.png',
                'img4' => 'assets/images/crossbows/fanghd-581308977.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Artemis Strike',
                'description' => 'Swift and deadly, forged for the goddess of the hunt.',
                'price' => 189.99,
                'manufacturer_id' => 3,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/657193_ts-2746782851.png',
                'img2' => 'assets/images/crossbows/how_far_can_crossbow_shoot_outdoorworldreviews-1400203458.png',
                'img3' => 'assets/images/crossbows/292144_ts-2963351509.png',
                'img4' => 'assets/images/crossbows/crossbows-416156808.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Medusa Gaze',
                'description' => 'A petrifying presence in battle, mirroring the stare of the gorgon.',
                'price' => 169.99,
                'manufacturer_id' => 2,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/r062_r470_01.20250410140045-791724732.png',
                'img2' => 'assets/images/crossbows/crossbow-shootout-twin-strike-3868259228.png',
                'img3' => 'assets/images/crossbows/150-lbs-Wood-Crossbow-1863153202.png',
                'img4' => 'assets/images/crossbows/fanghd-581308977.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Perseus Shot',
                'description' => 'Modeled after the slayer of monsters, reliable and heroic.',
                'price' => 199.99,
                'manufacturer_id' => 3,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/0ef92f4d5c630f353b7c4b9e80fd285e-4033638214.png',
                'img2' => 'assets/images/crossbows/crossbows-416156808.png',
                'img3' => 'assets/images/crossbows/607600_ts-213210129.png',
                'img4' => 'assets/images/crossbows/292144_ts-2963351509.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ares Thunderbolt',
                'description' => 'Embodies war and chaos with unmatched destructive power.',
                'price' => 189.5,
                'manufacturer_id' => 5,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/ek-archery-jaguar2-pro-black-reflexni-kuse-s-puskohledem-kr-7.webp',
                'img2' => 'assets/images/crossbows/F13-BKCB13-3449212446.png',
                'img3' => 'assets/images/crossbows/Barnett-Ghost-4102-2621310300.png',
                'img4' => 'assets/images/crossbows/0ffd538c315d3c85ae5842c4809b436a-2866547126.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hermes Dart',
                'description' => 'Lightweight, fast, and ready to fly with the speed of the messenger god.',
                'price' => 149.0,
                'manufacturer_id' => 2,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/292144_ts-2963351509.png',
                'img2' => 'assets/images/crossbows/fanghd-581308977.png',
                'img3' => 'assets/images/crossbows/iGlow-150-lb-Hunting-Compound-Crossbow-2574619735.png',
                'img4' => 'assets/images/crossbows/Barnett-Ghost-4102-2621310300.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Zeus Boltcaster',
                'description' => 'Harnessing divine power in each shot, a tool of dominance.',
                'price' => 219.9,
                'manufacturer_id' => 4,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/armbrust-matrix_310_paket-2666-218393819.png',
                'img2' => 'assets/images/crossbows/r055_01_xk7.20230110175312-622968906.png',
                'img3' => 'assets/images/crossbows/how_far_can_crossbow_shoot_outdoorworldreviews-1400203458.png',
                'img4' => 'assets/images/crossbows/ek-archery-jaguar2-pro-black-reflexni-kuse-s-puskohledem-kr-7.webp',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hephaestus Forgebolt',
                'description' => 'Crafted with precision worthy of the god of fire and blacksmithing.',
                'price' => 174.7,
                'manufacturer_id' => 2,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/292144_ts-2963351509.png',
                'img2' => 'assets/images/crossbows/Barnett-Ghost-4102-2621310300.png',
                'img3' => 'assets/images/crossbows/607600_ts-213210129.png',
                'img4' => 'assets/images/crossbows/F13-BKCB13-3449212446.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Odysseus Aim',
                'description' => 'Long-range reliability for the strategic warrior-king.',
                'price' => 164.3,
                'manufacturer_id' => 3,
                'product_type_id' => 2,
                'img1' => 'assets/images/crossbows/armbrust-matrix_310_paket-2666-218393819.png',
                'img2' => 'assets/images/crossbows/292144_ts-2963351509.png',
                'img3' => 'assets/images/crossbows/d6f8cb2488ec74d17076b267fc8daa63--crossbow-survival-gear-3605650570.png',
                'img4' => 'assets/images/crossbows/fanghd-581308977.png',
                'created_at' => $now,
                'updated_at' => $now,  
            ],
            [
                'name' => 'Apollos Reach',
                'description' => 'A lightweight slingshot fit for the sun god, delivering quick and precise shots.',
                'price' => 129.99,
                'manufacturer_id' => 2,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/00889fd955506c96ae77d8f651b6155a_large-1686287175.png',
                'img2' => 'assets/images/slings/05eaa2de8b0bf3e1bc117df6003bbf85_large-1474395364.png',
                'img3' => 'assets/images/slings/14379a-1157013504.png',
                'img4' => 'assets/images/slings/51R2TB4TCmL._SL500_-1078189806.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Athenas Precision',
                'description' => 'Crafted with the wisdom of the goddess of war, providing a steady aim for strategic hunters.',
                'price' => 119.49,
                'manufacturer_id' => 3,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/Powerful-Hunting-Slingshots-Professional-Tactical-Wrist-SlingShot-Rubber-Band-Tubing-Hunting-Shooting-Fishing-Equipment-PU-band-2985648519.png',
                'img2' => 'assets/images/slings/61ldF5Up2zL._AC_SL1000_-3752030266.png',
                'img3' => 'assets/images/slings/624ddec155615eabd5a053c012d635af_large-4166605043.png',
                'img4' => 'assets/images/slings/6526004ca67de8c535a93947dd1e24d3_large-2386333981.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hermes Flight',
                'description' => 'A quick, powerful slingshot designed for speed and agility, echoing the messenger gods swiftness.',
                'price' => 139.00,
                'manufacturer_id' => 1,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/92d079173cc441d4661112275d19ca11_large-2907889834.png',
                'img2' => 'assets/images/slings/711KICozjiL._AC_SL1500_-191283828.png',
                'img3' => 'assets/images/slings/712cDOKpmZL._SL1500_-2827892927.png',
                'img4' => 'assets/images/slings/719v2ny9WqL._AC_SL1500_-2780467879.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Zeus Fury',
                'description' => 'Harness the power of the skies with a slingshot built to deal devastating force.',
                'price' => 149.99,
                'manufacturer_id' => 5,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/Powerful-slingshots-fish-hunting-arrow-hunting-sling-shot-fishing-slingshots-4277643689.png',
                'img2' => 'assets/images/slings/71gqpBzTFYL._AC_SL1500_-1702584931.png',
                'img3' => 'assets/images/slings/AXBSLING03BK-3583209416.png',
                'img4' => 'assets/images/slings/ba07d4c8d769069719acd907333b2e52_large-2110418491.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Artemis Hunt',
                'description' => 'A sleek and agile slingshot perfect for stealthy hunts under the moonlight.',
                'price' => 115.50,
                'manufacturer_id' => 4,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/71-6DOIUnIL._AC_SL1500_-3286900255.png',
                'img2' => 'assets/images/slings/Barnett-Cobra-Outdoors-Slingshot_-3321158870.png',
                'img3' => 'assets/images/slings/edbf3a5ef51839eecf9a4122900e7e9e_large-1952179584.png',
                'img4' => 'assets/images/slings/Ergonomic-Camouflage-Powerful-Slingshot-Sniper-Catapult-Tactical-Hunting-Folding-Wrist-Support-Precision-Sling-Shot-62358701.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hades Grip',
                'description' => 'A dark, powerful tool, perfect for delivering quick shots in the shadows of the underworld.',
                'price' => 125.75,
                'manufacturer_id' => 2,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/HTB1IvdWNXXXXXc_XFXXq6xXFXXXs-4187656678.png',
                'img2' => 'assets/images/slings/HTB1oclYNVXXXXbMXXXXq6xXFXXX5-3073684116.png',
                'img3' => 'assets/images/slings/Outdoor-Traditional-Slingshot-Hunting-Tool-Single-String-Marble-Sling-Shot-Aluminum-Alloy-Catapult-Hunting-Slingshot-862239550.png',
                'img4' => 'assets/images/slings/PhotoRoom-20231124_160536-1793645050.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Poseidons Wave',
                'description' => 'A fluid, precise slingshot built to strike with the force of the oceans tide.',
                'price' => 139.99,
                'manufacturer_id' => 1,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/Powerful-Sling-Shot-Bamboo-Slingshot-Bow-Catapult-Popular-Outdoor-Hunting-Slingshot-Hunt-Tool-Accessories-for-Kids-1640261777.png',
                'img2' => 'assets/images/slings/product_16567_product_shots1_image-101415638.png',
                'img3' => 'assets/images/slings/Slingshot-Hunting-Powerful-Catapult-Camouflage-Stainless-Steel-Hunter-compound-bow-hunting-Sling-Shot-caza-With-Clamp-1833474358.png',
                'img4' => 'assets/images/slings/The-Scout-Hunting-Slingshot-3592686901.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ares Thunder',
                'description' => 'This slingshot channels the power of war, delivering a burst of force with every shot.',
                'price' => 145.60,
                'manufacturer_id' => 3,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/Barnett-Cobra-Outdoors-Slingshot_-3321158870.png',
                'img2' => 'assets/images/slings/AXBSLING01-729262081.png',
                'img3' => 'assets/images/slings/624ddec155615eabd5a053c012d635af_large-4166605043.png',
                'img4' => 'assets/images/slings/ba07d4c8d769069719acd907333b2e52_large-2110418491.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hephaestus Craft',
                'description' => 'Forged with fiery precision, this slingshot offers unparalleled reliability and strength.',
                'price' => 135.89,
                'manufacturer_id' => 4,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/HTB1IvdWNXXXXXc_XFXXq6xXFXXXs-4187656678.png',
                'img2' => 'assets/images/slings/HTB1oclYNVXXXXbMXXXXq6xXFXXX5-3073684116.png',
                'img3' => 'assets/images/slings/AXBSLING03BK-3583209416.png',
                'img4' => 'assets/images/slings/14379a-1157013504.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Medusas Vengeance',
                'description' => 'A slingshot with a petrifying presence, designed to strike with deadly accuracy.',
                'price' => 119.99,
                'manufacturer_id' => 2,
                'product_type_id' => 3,
                'img1' => 'assets/images/slings/AXBSLING01-729262081.png',
                'img2' => 'assets/images/slings/51R2TB4TCmL._SL500_-1078189806.png',
                'img3' => 'assets/images/slings/Ergonomic-Camouflage-Powerful-Slingshot-Sniper-Catapult-Tactical-Hunting-Folding-Wrist-Support-Precision-Sling-Shot-62358701.png',
                'img4' => 'assets/images/slings/Outdoor-Traditional-Slingshot-Hunting-Tool-Single-String-Marble-Sling-Shot-Aluminum-Alloy-Catapult-Hunting-Slingshot-862239550.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Apollos Arrow',
                'description' => 'Golden-tipped for unmatched precision, worthy of the sun god.',
                'price' => 29.99,
                'manufacturer_id' => 1,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/71hwONHxqbL._SL1500_-1269991412.png',
                'img2' => 'assets/images/arrows/Musen-Carbon-Archery-Arrows-1013910065.png',
                'img3' => 'assets/images/arrows/Top-10-Best-Arrows-for-Hunting-2877041867.png',
                'img4' => 'assets/images/arrows/51cSyhSSFjL-1121104959.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Artemis Feather',
                'description' => 'Balanced and deadly, crafted for the goddess of the hunt.',
                'price' => 34.5,
                'manufacturer_id' => 2,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/44494-01_1-1888633481.png',
                'img2' => 'assets/images/arrows/1-299-2729513352.png',
                'img3' => 'assets/images/arrows/Victory-Archery-V-TAC-23_f4159788da6a13a05c7755e7e3b29890-4169381793.png',
                'img4' => 'assets/images/arrows/51cpayfkunL-3333630687.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hades Piercer',
                'description' => 'Dark-fletched arrows that vanish into shadows.',
                'price' => 27.5,
                'manufacturer_id' => 3,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/th-3767279828.png',
                'img2' => 'assets/images/arrows/72cf014dce2943c8e3064868677cdb91-855770372.png',
                'img3' => 'assets/images/arrows/th-3767279828.png',
                'img4' => 'assets/images/arrows/71WtnwBQT1L._AC_SL1500_-1205029270.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Zeus Lightning Tip',
                'description' => 'Strikes like thunder, a bolt from Olympus.',
                'price' => 39.0,
                'manufacturer_id' => 4,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/maxima-hunter-900-2425494711.png',
                'img2' => 'assets/images/arrows/Top-10-Best-Arrows-for-Hunting-2877041867.png',
                'img3' => 'assets/images/arrows/MKFA26_5PCS__26255.1675697091-1726809822.png',
                'img4' => 'assets/images/arrows/1-306-1024x853-33435767.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ares Warshaft',
                'description' => 'Built for battle, these arrows never stray.',
                'price' => 31.2,
                'manufacturer_id' => 5,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/51cpayfkunL-3333630687.png',
                'img2' => 'assets/images/arrows/HuntingArrows-1733084781.png',
                'img3' => 'assets/images/arrows/PSE-416x416-1015699224.png',
                'img4' => 'assets/images/arrows/44494-01_1-1888633481.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hermes Glide',
                'description' => 'Swift as the wind, crafted for aerial precision.',
                'price' => 28.75,
                'manufacturer_id' => 1,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/Musen-Carbon-Archery-Arrows-1013910065.png',
                'img2' => 'assets/images/arrows/44494-01_1-1888633481.png',
                'img3' => 'assets/images/arrows/best-hunting-arrows-compound-recurve-bow-3705790845.png',
                'img4' => 'assets/images/arrows/1-299-2729513352.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Persephones Thorn',
                'description' => 'Elegant and sharp, kissed by the underworld.',
                'price' => 30.0,
                'manufacturer_id' => 2,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/18-25Pcs-30-80lbs-Tactical-Fiberglass-Arrow-80cm-Archery-Hunting-Nock-Proof-Fiberglass-Steel-Point-For-1860884974.png',
                'img2' => 'assets/images/arrows/51cSyhSSFjL-1121104959.png',
                'img3' => 'assets/images/arrows/Victory-Archery-V-TAC-23_f4159788da6a13a05c7755e7e3b29890-4169381793.png',
                'img4' => 'assets/images/arrows/MKFA26_5PCS__26255.1675697091-1726809822.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Athenas Insight',
                'description' => 'Smartly designed for perfect balance and flight.',
                'price' => 35.6,
                'manufacturer_id' => 3,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/th-3767279828.png',
                'img2' => 'assets/images/arrows/71hwONHxqbL._SL1500_-1269991412.png',
                'img3' => 'assets/images/arrows/44494-01_1-1888633481.png',
                'img4' => 'assets/images/arrows/1-306-1024x853-33435767.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Medusas Fang',
                'description' => 'Venomous precision that paralyzes prey mid-flight.',
                'price' => 32.95,
                'manufacturer_id' => 4,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/1-299-2729513352.png',
                'img2' => 'assets/images/arrows/PSE-416x416-1015699224.png',
                'img3' => 'assets/images/arrows/Musen-Carbon-Archery-Arrows-1013910065.png',
                'img4' => 'assets/images/arrows/best-hunting-arrows-compound-recurve-bow-3705790845.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dionysus Flight',
                'description' => 'Beautifully unpredictable, as wild as the god himself.',
                'price' => 26.6,
                'manufacturer_id' => 5,
                'product_type_id' => 4,
                'img1' => 'assets/images/arrows/72cf014dce2943c8e3064868677cdb91-855770372.png',
                'img2' => 'assets/images/arrows/PSE-416x416-1015699224.png',
                'img3' => 'assets/images/arrows/HuntingArrows-1733084781.png',
                'img4' => 'assets/images/arrows/71WtnwBQT1L._AC_SL1500_-1205029270.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Quiver of Delphi',
                'description' => 'Mystic quiver said to whisper prophecies of each shot.',
                'price' => 24.99,
                'manufacturer_id' => 2,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/arrow-quiver-back-shoulder-pouch-bag-pocket-969840992.png',
                'img2' => 'assets/images/other/1401575_2_1022x1022-2871409320.png',
                'img3' => 'assets/images/other/236111_ts-1492351205.png',
                'img4' => 'assets/images/other/Hunting-Archery-Arm-Guards-3-Strap-Safety-Protection-Protective-Gear-Leather-Shooting-Archery-Arm-Guard-Camo-3754294261.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Spartan Armguard',
                'description' => 'Forged for war, strong enough for a hoplite.',
                'price' => 18.50,
                'manufacturer_id' => 4,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/Hunting-Armguard-For-Archery-Hunting-Compound-Bow-Crossbow-Arm-Guards-Wrist-Protecter-8-6inch-camo-1999243627.png',
                'img2' => 'assets/images/other/301259_ts-3112455080.png',
                'img3' => 'assets/images/other/Archery-Holder-Back-Pack-Recurve-Bow-Arrow-Pouch-with-4-Tubes-for-Outdoor-Hunting-Shooting-Riding-2875487679.png',
                'img4' => 'assets/images/other/Camo-Archery-Arrow-Quiver-Bow-Bag-Traditional-Archery-Supplies-Pouch-Holder-For-Arrows-Shooting-Hunting-2292877143.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Bag of the Oracle',
                'description' => 'Carries not just arrows, but divine insight.',
                'price' => 32.00,
                'manufacturer_id' => 3,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/Archery-Bow-Bag-Pouch-Supplies-Shoulder-Aslant-Arrow-Quiver-Bundled-Bow-Bag-Processing-Quiver-Bag-3853870940.png',
                'img2' => 'assets/images/other/236111_ts-1492351205.png',
                'img3' => 'assets/images/other/Shoulder-Archery-Arrow-Back-Quiver-Holder-Bow-Storage-Bag-Pouch-Belt-Strap-Side-Camo-Outdoor-Archery-3862587253.png',
                'img4' => 'assets/images/other/301259_ts-3112455080.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Titan Guard',
                'description' => 'Protective armgear said to channel primordial power.',
                'price' => 21.45,
                'manufacturer_id' => 1,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/Hunting-Archery-Arm-Guards-3-Strap-Safety-Protection-Protective-Gear-Leather-Shooting-Archery-Arm-Guard-Camo-3754294261.png',
                'img2' => 'assets/images/other/1401575_2_1022x1022-2871409320.png',
                'img3' => 'assets/images/other/301259_ts-3112455080.png',
                'img4' => 'assets/images/other/Camo-Archery-Arrow-Quiver-Bow-Bag-Traditional-Archery-Supplies-Pouch-Holder-For-Arrows-Shooting-Hunting-2292877143.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hera’s Embrace',
                'description' => 'A noble quiver favored by queens and warriors alike.',
                'price' => 28.75,
                'manufacturer_id' => 5,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/Archery-Holder-Back-Pack-Recurve-Bow-Arrow-Pouch-with-4-Tubes-for-Outdoor-Hunting-Shooting-Riding-2875487679.png',
                'img2' => 'assets/images/other/T2eC16hHJGYE9nookQ_MBR5wJLY5Pw_60_57-1315381946.png',
                'img3' => 'assets/images/other/Shoulder-Archery-Arrow-Back-Quiver-Holder-Bow-Storage-Bag-Pouch-Belt-Strap-Side-Camo-Outdoor-Archery-3862587253.png',
                'img4' => 'assets/images/other/Hunting-Armguard-For-Archery-Hunting-Compound-Bow-Crossbow-Arm-Guards-Wrist-Protecter-8-6inch-camo-1999243627.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hephaestus Pack',
                'description' => 'Forged for endurance, sturdy as the god’s forge.',
                'price' => 35.90,
                'manufacturer_id' => 3,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/301259_ts-3112455080.png',
                'img2' => 'assets/images/other/Archery-Bow-Bag-Pouch-Supplies-Shoulder-Aslant-Arrow-Quiver-Bundled-Bow-Bag-Processing-Quiver-Bag-3853870940.png',
                'img3' => 'assets/images/other/236111_ts-1492351205.png',
                'img4' => 'assets/images/other/arrow-quiver-back-shoulder-pouch-bag-pocket-969840992.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nyx Armwrap',
                'description' => 'Shadowy protection inspired by the goddess of night.',
                'price' => 22.25,
                'manufacturer_id' => 2,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/T2eC16hHJGYE9nookQ_MBR5wJLY5Pw_60_57-1315381946.png',
                'img2' => 'assets/images/other/Hunting-Armguard-For-Archery-Hunting-Compound-Bow-Crossbow-Arm-Guards-Wrist-Protecter-8-6inch-camo-1999243627.png',
                'img3' => 'assets/images/other/Archery-Holder-Back-Pack-Recurve-Bow-Arrow-Pouch-with-4-Tubes-for-Outdoor-Hunting-Shooting-Riding-2875487679.png',
                'img4' => 'assets/images/other/1401575_2_1022x1022-2871409320.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Poseidon’s Carrier',
                'description' => 'Waterproof bag fit for sea-bound archers.',
                'price' => 30.00,
                'manufacturer_id' => 4,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/1401575_2_1022x1022-2871409320.png',
                'img2' => 'assets/images/other/Camo-Archery-Arrow-Quiver-Bow-Bag-Traditional-Archery-Supplies-Pouch-Holder-For-Arrows-Shooting-Hunting-2292877143.png',
                'img3' => 'assets/images/other/301259_ts-3112455080.png',
                'img4' => 'assets/images/other/Archery-Bow-Bag-Pouch-Supplies-Shoulder-Aslant-Arrow-Quiver-Bundled-Bow-Bag-Processing-Quiver-Bag-3853870940.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Aphrodite’s Quiver',
                'description' => 'Stylish and elegant, made for graceful warriors.',
                'price' => 26.40,
                'manufacturer_id' => 5,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/arrow-quiver-back-shoulder-pouch-bag-pocket-969840992.png',
                'img2' => 'assets/images/other/Shoulder-Archery-Arrow-Back-Quiver-Holder-Bow-Storage-Bag-Pouch-Belt-Strap-Side-Camo-Outdoor-Archery-3862587253.png',
                'img3' => 'assets/images/other/Hunting-Archery-Arm-Guards-3-Strap-Safety-Protection-Protective-Gear-Leather-Shooting-Archery-Arm-Guard-Camo-3754294261.png',
                'img4' => 'assets/images/other/236111_ts-1492351205.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chronos Strap',
                'description' => 'Time-tested protection for archers who endure.',
                'price' => 19.95,
                'manufacturer_id' => 1,
                'product_type_id' => 5,
                'img1' => 'assets/images/other/Hunting-Armguard-For-Archery-Hunting-Compound-Bow-Crossbow-Arm-Guards-Wrist-Protecter-8-6inch-camo-1999243627.png',
                'img2' => 'assets/images/other/236111_ts-1492351205.png',
                'img3' => 'assets/images/other/T2eC16hHJGYE9nookQ_MBR5wJLY5Pw_60_57-1315381946.png',
                'img4' => 'assets/images/other/Archery-Holder-Back-Pack-Recurve-Bow-Arrow-Pouch-with-4-Tubes-for-Outdoor-Hunting-Shooting-Riding-2875487679.png',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        
        
        
        DB::table('products')->insert($products);

    }
}
